### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by hahmad2008** [andgoldschmidt/pyprotoclust#1]
Thanks for sharing this package. I can't install the package via pip or setup package. could you help me in that?

- `pip install . `

> ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpa8ydsv1m Check the logs for full command output.

- with `pip install pyprotoclust`

>ERROR: No matching distribution found for pyprotoclust

**Comment by andgoldschmidt** [comment]
Hi! Which version of python are you using? This package uses c++ so
https://pypi.org/project/pyprotoclust/#files lists the compiled packages
that have been built (supporting python 3.7 and 3.8). My guess is this is
your issue.

If you need to use an older version of python, let me know and I can
release one. I'll also remember to tag the supported python more
specifically in the next release.

Best,
Andy
