### ISSUE TITLE
Package does not have Windows wheels

### ISSUE THREAD

**Issue by Jbarrers9740** [andgoldschmidt/pyprotoclust#2]
Hi! I am using Windows 10 and I am trying to install the package with:

`pip install pyprotoclust`

I have tried even creating different conda environments, but the same error always arrises:

```
Building wheels for collected packages: pyprotoclust
  Building wheel for pyprotoclust (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyprotoclust (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      A setup.py file already exists. Using it.
      Traceback (most recent call last):
        File "C:\Users\gorgo\AppData\Local\Temp\pip-install-54lp9uet\pyprotoclust_362cf845644e40b698d9726acc64ba2a\setup.py", line 2, in <module>
          from setuptools import setup
      ModuleNotFoundError: No module named 'setuptools'
      Traceback (most recent call last):
        File "D:\Programas\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\Programas\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Programas\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\gorgo\AppData\Local\Temp\pip-build-env-b672qip5\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 68, in build_wheel
          return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
        File "C:\Users\gorgo\AppData\Local\Temp\pip-build-env-b672qip5\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 78, in make_in
          wb.build()
        File "C:\Users\gorgo\AppData\Local\Temp\pip-build-env-b672qip5\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 110, in build
          self._build(zip_file)
        File "C:\Users\gorgo\AppData\Local\Temp\pip-build-env-b672qip5\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 162, in _build
          self._run_build_command(setup)
        File "C:\Users\gorgo\AppData\Local\Temp\pip-build-env-b672qip5\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 190, in _run_build_command
          subprocess.check_call(
        File "D:\Programas\anaconda3\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:/Programas/anaconda3/python.exe', 'C:\\Users\\gorgo\\AppData\\Local\\Temp\\pip-install-54lp9uet\\pyprotoclust_362cf845644e40b698d9726acc64ba2a\\setup.py', 'build', '-b', 'C:\\Users\\gorgo\\AppData\\Local\\Temp\\pip-install-54lp9uet\\pyprotoclust_362cf845644e40b698d9726acc64ba2a\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyprotoclust
Failed to build pyprotoclust
ERROR: Could not build wheels for pyprotoclust, which is required to install pyproject.toml-based projects
```

I have checked my installation and `setuptools` is correctly installed. I have also tried with `python -m pip install --upgrade pip setuptools wheel`, and with `python -m pip install --upgrade setuptools` but they do not solve the problem either.

**Comment by andgoldschmidt** [comment]
The installer is trying to build for the package. I'm not sure why it's failing because my pyproject.toml has setuptools as a [build-system] required package.

As for why the build is triggered, this will happen if none of the pre-built wheels on pypi match (https://pypi.org/project/pyprotoclust/0.1.0/#files).  I have built wheels for 3.7 and 3.8 on linux, but not windows.

**Comment by andgoldschmidt** [comment]
I was able to build and test windows wheels by building from source using poetry without any trouble, https://pyprotoclust.readthedocs.io/en/latest/installation.html

I guess there might be an issue with pip trying to build something designed to be built with poetry which would explain the setuptools complaint. It would be good for me to upload a new version of the package which includes windows wheels when I have a chance, so I'll try to do that.

**Comment by Josue9740** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Segoe UI Symbol";
	panose-1:2 11 5 2 4 2 4 2 2 3;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 3.0cm 70.85pt 3.0cm;}
div.WordSection1
	{page:WordSection1;}

**Comment by Jbarrers9740** [comment]
Hi Andy,
 
First of all, thank you so much for your prompt response and for your work. I have read your comments, so I will be waiting for the new Windows fixes since I cannot use Poetry. 

In the meantime, I think you forgot to attach the environment .yml file (I cannot see it). Could you send it, please?

Regards,

**Comment by andgoldschmidt** [comment]
Poetry builds in a local project environment, and it should grab all necessary dependencies (https://pyprotoclust.readthedocs.io/en/latest/installation.html)

If you want, you can install poetry (https://python-poetry.org/docs/#installation) and try to build wheels for your system by running
```
poetry shell
poetry install -E cython
poetry build
```
within the top level of the pyprotoclust package.

The conda environment can satisfy dependencies of the pip pyprotoclust package, but won't fix the build issue. That being said, here is the environment I used to run the code in the README with the wheels I built following the aforementioned instruction:

```
name: test_pyprotoclust
channels:
  - defaults
dependencies:
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - ca-certificates=2022.3.29=haa95532_1
  - certifi=2021.10.8=py37haa95532_2
  - colorama=0.4.4=pyhd3eb1b0_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2021.4.0=haa95532_3556
  - ipython=7.31.1=py37haa95532_0
  - jedi=0.18.1=py37haa95532_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - numpy=1.21.5=py37h7a0a035_1
  - numpy-base=1.21.5=py37hca35cd5_1
  - openssl=1.1.1n=h2bbff1b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py37haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.7.13=h6244533_0
  - scipy=1.7.3=py37h0a974cb_0
  - setuptools=61.2.0=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py37haa95532_2
  - pip:
    - pyprotoclust==0.1.0
    - tqdm==4.64.0
prefix: D:\Programs\Anaconda3\envs\test_pyprotoclust
```

**Comment by andgoldschmidt** [comment]
I added wheels for windows to the 0.1 release, let me know if these address the problem

**Comment by Jbarrers9740** [comment]
Hi!

Definitely, it works now! Thank you so much!
